apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application1-kustomize
  namespace: openshift-gitops
spec:
  destination:
    name: wl00
    namespace: application1
  project: applications
  source:
    path: applications/application1/kustomize/overlay
    repoURL: 'https://github.com/robertsandoval/gitops.git'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

