apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application3-appset
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster: managed
  template:
    metadata:
      name: '{{name}}-httpd-App3-fromAppSetCG'
    spec:
      project: sync-demo
      syncPolicy:
        automated:
          prune: false
      source:
        repoURL: https://github.com/robertsandoval/gitops.git
        targetRevision: master
        path: syncing-demo/application3/base
      destination:
        server: '{{server}}'
        namespace: application3-httpd
