apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application2
  namespace: openshift-gitops
spec:
  destination:
    name: wl00
    namespace: application2
  project: applications
  source:
    path: applications/application2/default
    repoURL: 'https://github.com/robertsandoval/gitops.git'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

